version: '3.8'

services:
  "postgres":
    container_name: "pg"
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
  "redis":
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
volumes:
  pg-data:
  redis-data: